### ISSUE TITLE
what to do with old files?

### ISSUE THREAD

**Issue by Jenso666** [codeQuake/Fireball#104]
If users uploaded files to FileManagement-System before Beta 8, the files will not work anymore in Beta 8. What to do? It's because the files were stored in a different way, without fileHash & in subfolders.
Is there a possibility to create a hash & move them by updating the system?

**Comment by ray176** [comment]
You can retroactively generate the file hash by executing sha1_file for every file. The subfolder name equals the first two characters of the file hash.
