### ISSUE TITLE
On Editing Content => parentID is not loaded

### ISSUE THREAD

**Issue by Jenso666** [codeQuake/Fireball#112]

**Comment by Jenso666** [comment]
additional information: only if one of the parent-Contents is disabled

**Comment by ray176** [comment]
Hm, can't reproduce that with the given information.

Following content structure:
- a
  - b
    - c

`a` and `b` are both disabled. When editing `c`, `b` is correctly preselected as parent content.

**Comment by Jenso666** [comment]
I will check that again
