### ISSUE TITLE
Import Bugs

### ISSUE THREAD

**Issue by Jenso666** [codeQuake/Fireball#122]
Things that do not work regarding the import/export

- [ ] wrong content parents
- [ ] content settings -> not imported in some cases, like h1/h2/h3/.. for headings
- [ ] empty result stylesheet to page table

**Comment by mutec** [comment]
point 1: dc448e110f7ec5613d44a4584adc8861799b2a11 and 037243602e432c111b6ff79a91a72175268a96b8
point 2: 9453bff0f47ad85e04dd42dec9971966762fbfe5
point 3: 41ae48d75200cdf8bc59e7f848b13bb45d8391e9

that should do it

**Comment by Jenso666** [comment]
When having a gallery content type the import fails, because $tmpData['imageIDs'] is used as an array in foreach but has a string value (the IDs separated by commas). i suggest using explode in line 467
```php 
foreach (explode(',', $tmpData['imageIDs']) as $fileID) {
[...]
}
```

after adding this the import of my testfile works perfect

**Comment by mutec** [comment]
That's strange. When I use var_dump($tmpData['imageIDs']); in Line 466 I get an array:

array(15) {
  [0]=>
  string(4) "5588"
  [1]=>
  string(4) "5589"
  [2]=>
  string(4) "5586"
  [3]=>
  string(4) "5584"
  [4]=>
  string(4) "5583"
  [5]=>
  string(4) "5585"
  [6]=>
  string(4) "5587"
  [7]=>
  string(4) "5591"
  [8]=>
  string(4) "5590"
  [9]=>
  string(4) "5593"
  [10]=>
  string(4) "5595"
  [11]=>
  string(4) "5592"
  [12]=>
  string(4) "5594"
  [13]=>
  string(4) "5597"
  [14]=>
  string(4) "5596"
}

**Comment by Jenso666** [comment]
Hmm I got "21,22,24,27" o.O

**Comment by mutec** [comment]
Did you export with the current fileversion or using a Beta 7-Export? That's the only possible reason I can image at the moment.

**Comment by Jenso666** [comment]
I copy pasted the backuphandler file into my first testing system, downloaded the backup and imported this into a clean installation system with 2.0.0 Beta 8

**Comment by Jenso666** [comment]
Export file has ´´´YToxOntzOjg6ImltYWdlSURzIjtzOjExOiIyMywyNCwyNiwyNSI7fQ==´´´ which is decoded to
a:1:{s:8:"imageIDs";s:11:"23,24,26,25";}

**Comment by Jenso666** [comment]
AAAAAH found it! The content was created with beta 7 - so the content type uses the compatibility mode
```php
//neccessary for old data (version 2.0.0 Beta 7 or older)
		if (is_string($content->imageIDs)) $imageIDs = explode(',', $content->imageIDs);
```
GalleryContentType line 26-27

so there are two options: update data on update or checking whether tmpData is string or array

**Comment by mutec** [comment]
Ah okay. You may try it with this: 08c7df78bfcc6721e7a06d475a6890470e10b956
Should work for arrays and strings.

**Comment by Jenso666** [comment]
This works fine :)
