### ISSUE TITLE
Remove possibility to specify content css id

### ISSUE THREAD

**Issue by ray176** [codeQuake/Fireball#126]
I propose to remove the possibility to specify the css id for contents. They give the danger that admins set an id multiple times on a page, leading to unexpected results.
Instead, every content should get an id according to a general pattern, e.g. `cmsContent{contentID}`.

Related bugs:
- http://codequake.de/forum/index.php/Thread/2313-Selbe-tab-Id-beim-kopieren-von-Inhalten/

**Comment by Jenso666** [comment]
:+1:
