### ISSUE TITLE
Pagepicker for Notices

### ISSUE THREAD

**Issue by mutec** [codeQuake/Fireball#135]
Implement a page-picker to enable precise selection of pages where you want to display a notice.
Compare "Thread" by WBB where the user can choose multiple boards to display.

**Comment by jacboy** [comment]
Due the unfinished implementation of this feature, I think it is better to implement that in v2.1.....
![bildschirmfoto 2015-05-19 um 18 26 49](https://cloud.githubusercontent.com/assets/6690861/7708231/a3d81774-fe54-11e4-8dd1-c2c2d56ee20a.png)
