### ISSUE TITLE
Nachrichtenbild von RSS-Feeds

### ISSUE THREAD

**Issue by thewaiters** [codeQuake/Fireball#152]
Im ACP kann man bei einem RSS kein Nachrichtenbild hinzufügen. Das Dialogfenster geht nicht auf. Diese Fehler werden in der Konsole angezeigt:

Uncaught TypeError: Cannot read property 'extend' of undefined
Uncaught TypeError: Cannot read property 'FormGuard' of undefined

**Comment by mutec** [comment]
https://github.com/codeQuake/Fireball-News-RSS-Reader/commit/52a361ad6fcbec89a54e052fa7b8cb8d9bd3e0dd
https://github.com/codeQuake/Fireball-News-RSS-Reader/commit/b93957d764c9b7a4e2052b194f423880aba9bff2
